### ISSUE TITLE
When you start having wars, your cities will disappear.

### ISSUE THREAD

**Issue by cbbcbail** [EcoGame/Eco#15] opened 2015-05-11 20:05 UTC
When they come back, they don't have names.

**Comment by phillip-h** [comment] 2015-05-13 23:07
Possible related to the fact that war can be triggered faster than the update tick runs, causing the real population and the world population to desynchronize.

**Comment by phillip-h** [comment] 2015-05-14 01:38
Caused by pop auto-balancing, not really a bug.

**Comment by phillip-h** [comment] 2015-05-14 01:47
Fixed by adding cooldown to pop auto-balance after a war

**Closed as completed by phillip-h** 2015-05-14 01:47 UTC
Labels: enhancement
